apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-demo-db
spec:
  template:
    spec:
      containers:
        - name: tilt-demo-db
          env:
          - name: POSTGRES_HOST
            value: db
          - name: POSTGRES_PORT
            value: "5432"
          envFrom:
          - secretRef:
              name: db-secret
