apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml

namespace: tilt-demo-db

secretGenerator:
- literals:
  - POSTGRES_DB=default
  - POSTGRES_USER=default
  - POSTGRES_PASSWORD=default
  name: db-secret

patches:
- path: app-patch.yaml
