apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: "postgres:14"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
          resources:
            limits:
              cpu: "1"
              memory: "521Mi"
            requests:
              cpu: "125m"
              memory: "256Mi"
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-volume-claim
